### ISSUE TITLE
Enforce unit system hygeine 

### ISSUE THREAD

**Issue by cbolisetti** [idaholab/mastodon#197]
While we are trying to add more and more tests, examples, and code, we need to be careful and be more transparent with the engineering units we are using in the test files and examples. I suggest the following: 

- Use the metric system as much as possible (m, Kg, sec, C), since it makes sense.
- Enforce the specification of the unit system being used at the beginning of all input files. 
@aeslaughter can we enforce something like that?

@sveerara @hoffwm @aeslaughter  let me know what you think.

**Comment by aeslaughter** [comment]
No, we don't have any means to enforce a unit system. Creating a means would be a large project that we don't have time to build.

**Comment by cbolisetti** [comment]
I don't think we need to enforce a unit system. Just a line in each input file; something like:

```
# units: Kg m sec C
```

Can we do that?

**Comment by cbolisetti** [comment]
Looks like the only way we can do this right now is to enforce it while reviewing. Let's try to do that for now.
