### ISSUE TITLE
Gravity Kernel with ISoilAction

### ISSUE THREAD

**Issue by crswong888** [idaholab/mastodon#235]
I've noticed that the `Gravity` kernel does not pick up on the soil density set in the ISoilAction block. You also cannot simultaneously use a `GenericConstantMaterial` for the density of the soil block if you are using ISoilAction. An easy work-around would be to just set up I-Soil using `ComputeISoilStress` and then you can use `GenericConstantMaterial` for the density, but if we can somehow make the `Gravity` kernel work with ISoilAction that would be more convenient.

**Comment by sveerara** [comment]
@crswong888 and I looked at the example more closely and we have figured out that the Gravity kernel picks up the soil density that is set in the ISoilAction. So, I am closing this issue.
