### ISSUE TITLE
Correct compile time error in MASTODON corresponding to Moose PR #14221

### ISSUE THREAD

**Issue by sveerara** [idaholab/mastodon#258]
Mastodon is throwing an error after changes in the Moose PR 14221. 

```
/opt/civet/build_0/mastodon/src/transfers/HazardCurveTransfer.C:4:10: fatal error: Piecewise.h: No such file or directory
 #include "Piecewise.h"
          ^~~~~~~~~~~~~
```

**Comment by bwspenc** [comment]
I recently merged that MOOSE PR. The change that @sveerara proposed doesn't quite work because a few things have changed since that time. I have a new PR that I will submit to close this issue.
