### ISSUE TITLE
Update MASTODON install instructions (using conda to activate MOOSE)

### ISSUE THREAD

**Issue by somu15** [idaholab/mastodon#307]
With the `conda activate moose` and `conda update --all` commands, libmesh need not be manually built or updated. Please see instructions [here](https://mooseframework.inl.gov/getting_started/installation/conda.html) on the MOOSE website. This issue can make MASTODON up-to-date with the MOOSE developments.

**Comment by cbolisetti** [comment]
Yes, this has existed for a while but some of our tests will fail if we use the conda package because the conda package uses more recent compilers. When I tried this several months ago, quite a few tests failed, but @hoffwm mentioned that only 1-2 tests fail now. We might only have to regold these. @hoffwm since you are already on conda, can you verify this and regold them? @somu15 can then update the instructions.

**Comment by lynnmunday** [comment]
I put in similar instructions for building blackbear with conda since it has the same problems as mastadon

https://mooseframework.org/blackbear/source/materials/NEMLStress.html

**Comment by lynnmunday** [comment]
@cbolisetti @hoffwm   I can run the tests, I'm using conda.  Are they all regression tests?

**Comment by lynnmunday** [comment]
test:materials/isoil.data_file .............................................................. FAILED (EXODIFF)
test:bcs/seismic_force.seismic_force_test_z ................................................. FAILED (EXODIFF)

These two fail
You want them reblessed?

**Comment by cbolisetti** [comment]
@lynnmunday thanks for running those! Yes, please rebless them if the differences are really small. If not, we'll have to look into it in more detail. Can you post part the exodiff results here?

**Comment by cbolisetti** [comment]
Why does mastadon need the full version of boost from libmesh? Ben changed the stochastic_tools distributions over to not use boost that we might be able to call directly. Would that work? Blackbear needed boost for other reasons.
> 

We need to remove the BOOST dependency -- that's on my list of things to do..

**Comment by lynnmunday** [comment]
> We need to remove the BOOST dependency -- that's on my list of things to do..
  Do you have an issue for this, I can do it.

**Comment by lynnmunday** [comment]
test:materials/isoil.data_file:   --------- Time step 782, 7.8100000e+00 ~ 7.8100000e+00, rel diff:  0.00000e+00 ---------
test:materials/isoil.data_file: Global variables:
test:materials/isoil.data_file: Nodal variables:
test:materials/isoil.data_file: Element variables:
test:materials/isoil.data_file:   --------- Time step 783, 7.8200000e+00 ~ 7.8200000e+00, rel diff:  0.00000e+00 ---------
test:materials/isoil.data_file: Global variables:
test:materials/isoil.data_file:    accel_6z      rel diff:  3.4966884e-08 ~  3.4965971e-08 = 2.61060e-05 (FAILED)
test:materials/isoil.data_file: Nodal variables:
test:materials/isoil.data_file:    accel_z  rel diff:  3.4966884e-08 ~  3.4965971e-08 = 2.61060e-05 (node 6)



test:bcs/seismic_force.seismic_force_test_z:   --------- Time step 177, 1.7600000e+00 ~ 1.7600000e+00, rel diff:  0.00000e+00 ---------
test:bcs/seismic_force.seismic_force_test_z: Global variables:
test:bcs/seismic_force.seismic_force_test_z: Nodal variables:
test:bcs/seismic_force.seismic_force_test_z: Element variables:
test:bcs/seismic_force.seismic_force_test_z:   --------- Time step 178, 1.7700000e+00 ~ 1.7700000e+00, rel diff:  0.00000e+00 ---------
test:bcs/seismic_force.seismic_force_test_z: Global variables:
test:bcs/seismic_force.seismic_force_test_z: Nodal variables:
test:bcs/seismic_force.seismic_force_test_z:    accel_z  rel diff: -1.2179614e-03 ~ -1.2179341e-03 = 2.23994e-05 (node 17)
test:bcs/seismic_force.seismic_force_test_z: Element variables:

**Comment by lynnmunday** [comment]
> @lynnmunday thanks for running those! Yes, please rebless them if the differences are really small. If not, we'll have to look into it in more detail. Can you post the exodiff results here?

I pasted the exodiff above.  
For seismic force, 1e-3 is really small, the max for accel_z is 206.55778
For isoil.data_file. accel_6z is 1e-1. and disp_6z is 8e-5

**Comment by cbolisetti** [comment]
Yeah, those look really small -- can you please regold and create a PR? I wanted to do it earlier but converting back and forth from conda to the MOOSE package takes a lot of time..

**Comment by lynnmunday** [comment]
> Yeah, those look really small -- can you please regold and create a PR? I wanted to do it earlier but converting back and forth from conda to the MOOSE package takes a lot of time..
Its the pr above that references this issue.
