### ISSUE TITLE
MASTODON Logo With a Transparent Background

### ISSUE THREAD

**Issue by crswong888** [idaholab/mastodon#318]
It would be nice if there were a .png file for the MASTODON Logo that has a transparent background. Does anyone know if this exists? 

This would be useful for situations where the color of the surrounding layout isn't white, such as the appearance of the website when using dark mode on Apple devices. I also recently created a GIF rendering of a model that uses a black background, for which I wanted to use the MASTODON logo at `doc/content/media/mastodon_logo.png`, but, because it's white background contrasted, I ended up just using the MOOSE logo for aesthetic purposes.

If anyone has copies of the original logo design files, I can try to make a transparent version myself. Let me know!

**Comment by cbolisetti** [comment]
I noticed this a few weeks ago when I started using dark mode. I'll have to ask graphics to make something for us.

**Comment by crswong888** [comment]
@cbolisetti, okay. If theres anything I can do to help, let me know!
