### ISSUE TITLE
Required parameters for ComputeLRIsolatorElasticity

### ISSUE THREAD

**Issue by samyogshr** [idaholab/mastodon#326]
Is 'alpha' ratio of post-yield to initial shear stiffness of bearing rather than yield displacement of bearing? (Unit: Dimensionless)
Is 'fy' yield force rather than yield stress of bearing? (Unit: Force)

**Comment by somu15** [comment]
@cbolisetti Can you please look at this?

**Comment by cbolisetti** [comment]
@samyogshr it looks like qYield might actually be the force and not the stress. Alpha is unitless though. Please post this on google groups so that Sharath, who is the author of that code, can respond. If we need to change the documentation or the code, we can come back to this issue here.

**Comment by SaiSharathParsi1995** [comment]
@cbolisetti and @samyogshr , I apologize for the delayed reply. I have replied to the question in the google group and pasting it below.

Yes,

i) alpha is the ratio of post-yield shear stiffness to the initial elastic shear stiffness of the bearing. Unit is dimensionless
ii) fy is the yield strength (i.e., force) of the bearing and not stress. 

The documentation and the source files will need to be updated.

**Comment by SaiSharathParsi1995** [comment]
@cbolisetti and @somu15 , I was just wondering if this issue has been resolved. Let me know if I can be of any assistance
