### ISSUE TITLE
Documentation falure

### ISSUE THREAD

**Issue by loganharbour** [idaholab/mastodon#361]
## Bug Description
Documentation is failing, preventing a MOOSE submodule update.

## Steps to Reproduce
See https://civet.inl.gov/job/662526/.

Update the submodule manually and fix the doc issue.

## Impact
Make things green again.

FYI @cbolisetti I don't plan on fixing this - hopefully you can delegate.

**Comment by cbolisetti** [comment]
I thought we fixed this -- not sure what is happening. Will look into it.

**Comment by cbolisetti** [comment]
Tagging @bwspenc 

I tried to reproduce this locally and It looks like NEML is not even being pulled, so it is not being compiled, and therefore the documentation is failing. I think we need to make a small modification to the CIVET recipe? Here's what's happening now: 

```
BUILD_ROOT/mastodon/: git submodule update --init
Submodule 'blackbear' (https://github.com/idaholab/blackbear.git) registered for path 'blackbear'
Submodule 'moose' (https://github.com/idaholab/moose.git) registered for path 'moose'
From https://github.com/idaholab/blackbear
   4ce77a4..d93f105  devel      -> origin/devel
   f581f19..d49b908  master     -> origin/master
Submodule path 'blackbear': checked out 'd49b908b0ba0ad1ec9a3d42cfaad616d68875f89'
Submodule path 'moose': checked out 'de5b71122f7b291f3084bad610b83a6790af7a87'
BUILD_ROOT/mastodon/: git submodule foreach --recursive git submodule update
Entering 'blackbear'
Entering 'moose'
BUILD_ROOT/mastodon/: git submodule status --recursive
 d49b908b0ba0ad1ec9a3d42cfaad616d68875f89 blackbear (remotes/origin/master)
-23dd2cdb83057fdd17a37fa19f4592c54f821dbf blackbear/contrib/neml
 de5b71122f7b291f3084bad610b83a6790af7a87 moose (snapshot-20-10-27-17800-gde5b71122f)
-79d440f4767c1500c766276f2df9235ea75b8fca moose/large_media
-c70ab40900490f44391f1b891c8c3731c45f0cf1 moose/libmesh
-94fb59f4ccbca51eac1f1822a93eb939f0d846b6 moose/petsc
BUILD_ROOT/mastodon/: make -j 32
WARNING: Not building with NEML because contrib/neml submodule is not present and NEML_DIR was not set to a valid NEML checkout
```

**Comment by loganharbour** [comment]
Ping @aeslaughter - I think he hit the same issue, or a similar issue with Pronghorn.

**Comment by aeslaughter** [comment]
Compiling NEML seems like to correct solution.

**Comment by bwspenc** [comment]
Sorry that we keep breaking your build because of these issues!

I don't think that actually shows up in the civet recipes themselves, but rather, it's in the functions that get triggered by the recipes. Has this been broken for a while? I'm happy to talk through it with you.

**Comment by loganharbour** [comment]
I'm glad to assist with the recipes - let me know

**Comment by loganharbour** [comment]
This issue was resolved by ensuring that the blackbear/contrib/neml submodule is initialized and updated during the MOOSE submodule update recipe.
