### ISSUE TITLE
Update deprecated code in Mastodon Master Action

### ISSUE THREAD

**Issue by dschwen** [idaholab/mastodon#387]
## Reason
Mastodon triggers framework deprecation warnings as variables are still added using an outdated API. We also need to make Mastodon compatible with https://github.com/idaholab/moose/issues/18311

## Design
Most of what the Mastodon Model Action does needs to be in Tensor Mechanics. This will allow us to update the syntax and use the additional functionality form the Tensor Mechanics Master action. All objects created by the Mastodon Model Action actually live in the TM module. 

## Impact
Added capability, fixed deprecations

**Comment by cbolisetti** [comment]
@dschwen can I close this issue?

**Comment by dschwen** [comment]
Yes
