### ISSUE TITLE
a 'SubdomainBoundingBox' is not a registered object

### ISSUE THREAD

**Issue by HakunanMatatat** [idaholab/mastodon#448]
![image](https://github.com/idaholab/mastodon/assets/56817048/48f8cf47-fab6-480b-be29-bd83f20f57af)

I run the example ex07. It does not work when I export MOOSE_LiBARY_PATH=$MOOSE_LIBRARY_PATH:$HOME/projects/mastodon/lib. 

![image](https://github.com/idaholab/mastodon/assets/56817048/83e2bedf-a567-4cf7-8b58-8df371295938)

That's the finding result.

I don't know if Mastodon is compiled well because the ./run_tests turn out many errors.

**Comment by GiudGiud** [comment]
you should not need to export MOOSE_LIBRARY_PATH and if you did you would point to moose not mastodon/lib

**Comment by HakunanMatatat** [comment]
Still the same problem. May I need to compile again. The moose in mastodon was tried twice during git but was not downloaded. I git it separately and there was an issue with the commit id during compilation, but it was successfully compiled. Except for big_model. i running smoothly and having output, everything else has similar issues. Do I need to add anything to the path?

![image](https://github.com/idaholab/mastodon/assets/56817048/35cf87a3-65a7-45aa-87a1-f50b7028850e)

**Comment by GiudGiud** [comment]
`'ParsedAddSidesetGenerator` does not exist. 
use this
https://mooseframework.inl.gov/source/meshgenerators/ParsedGenerateSideset.html

The apps are compiled in mastodon/build
