### ISSUE TITLE
Add MASTODON Installation Instructions to Online Documentation

### ISSUE THREAD

**Issue by colejust** [idaholab/mastodon#82]

**Comment by cbolisetti** [comment]
@colejust can this issue be closed since installation instructions have been added?

**Comment by colejust** [comment]
Yes

Sent from my iPhone

On Dec 14, 2017, at 5:38 PM, Chandu Bolisetti <notifications@github.com>
wrote:

@colejust
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_colejust&d=DwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=SIO4TqFddOdYzQ8FOpXQeb2uGJc62Ppb2_bVwsDB2gY&m=pY0qeK8mvyYxoExxP-yh3mmeZG9M-eWf5FHwaI-dl6s&s=2nF0lAD42v99OaKJefQRnJyDv22i5EwjEBbakmFWft8&e=>
can this issue be closed since installation instructions have been added?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_mastodon_issues_82-23issuecomment-2D351879017&d=DwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=SIO4TqFddOdYzQ8FOpXQeb2uGJc62Ppb2_bVwsDB2gY&m=pY0qeK8mvyYxoExxP-yh3mmeZG9M-eWf5FHwaI-dl6s&s=mWC4ik-FDfdGh_8M5sUK9Mx2dGsrMKOJ4Gxxa1nGRdM&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASanzJAPJs8nJUla4Pw6ztOgZEHrijovks5tAb9wgaJpZM4PzR-2DJ&d=DwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=SIO4TqFddOdYzQ8FOpXQeb2uGJc62Ppb2_bVwsDB2gY&m=pY0qeK8mvyYxoExxP-yh3mmeZG9M-eWf5FHwaI-dl6s&s=eDZdBU_w9j7-PXja-MQiVOi6JJYLAy0IO9rRg5w10L8&e=>
.
