### ISSUE TITLE
MASTODON Page Installation Issue

### ISSUE THREAD

**Issue by colejust** [idaholab/mastodon#97]
on the install part of MASTODON:

(3) MOOSE Environment package (choose one):
Sierra 10.12: moose-environment-36_sierra-10.12_x86_64.pkg
El Capitan 10.11: moose-environment-86_elcapitan-10.11_x86_64.pkg

When I click on Sierra I get:

Not Found

The requested URL /static/media/uploads/files/moose-environment-36_sierra-10.12_x86_64.pkg was not found on this server.

Apache/2.2.22 (Ubuntu) Server at mooseframework.org Port 80

**Comment by aeslaughter** [comment]
I can't reproduce this, the links seem to work for me. I think this was fixed with the most recent update of MOOSE.

**Comment by hoffwm** [comment]
@aeslaughter click the sierra link here: http://mooseframework.org/mastodon/getting_started/macos/index.html
I get the error on that link, you don't? I am currently building the latest Mastodon/MOOSE to see if I get the error there as well.

**Comment by aeslaughter** [comment]
I don't get the error.

**Comment by hoffwm** [comment]
You win...error is gone
